# Generated by Django 5.2 on 2025-05-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_barber_specialclosingday_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_slot_size',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='service',
            name='slots_required',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
