# Generated by Django 5.2 on 2025-05-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_service_default_slot_size_service_slots_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
    ]
