# Generated by Django 5.2 on 2025-05-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_shop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
    ]
