# Generated by Django 5.2 on 2025-05-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='created_at',
        ),
    ]
