# Generated by Django 5.2 on 2025-05-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_shop_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
    ]
