# Generated by Django 5.2 on 2025-06-13 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_booking_delete_appointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='shop',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='shop.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together={('shop', 'day_of_week')},
        ),
    ]
