# Generated by Django 5.2 on 2025-06-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_booking_options_remove_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('wallet', 'Wallet')], default='razorpay', max_length=20),
        ),
    ]
