# Generated by Django 5.2 on 2025-07-14 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_bookingfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barber',
        ),
        migrations.AlterUniqueTogether(
            name='shopreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shopreview',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopreview',
            name='user',
        ),
        migrations.AlterField(
            model_name='bookingfeedback',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.shop'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ShopReview',
        ),
    ]
