# Generated by Django 5.2 on 2025-07-31 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_temporaryslotreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialclosingday',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_closing_days', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='specialclosingday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='specialclosingday',
            unique_together={('shop', 'date')},
        ),
    ]
