# Generated by Django 5.2 on 2025-08-07 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_specialclosingday_shop_alter_specialclosingday_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temporaryslotreservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='temporaryslotreservation',
            name='service_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporaryslotreservation',
            name='service_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='temporaryslotreservation',
            name='total_service_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddIndex(
            model_name='temporaryslotreservation',
            index=models.Index(fields=['user', 'shop', 'appointment_date'], name='shop_tempor_user_id_fbbe0a_idx'),
        ),
    ]
