# Generated by Django 5.2 on 2025-06-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Current latitude of user', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Current longitude of user', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_enabled',
            field=models.BooleanField(default=False, help_text='Whether user has enabled location services'),
        ),
    ]
